const VOCABULARY = [
    {name: 'acquired resistance', subclassof: ['resistance'], oppositeof: ['innate resistance']},
    {name: 'amplification', subclassof: ['copy gain']},
    {name: 'associated with'},
    {name: 'biological'},
    {name: 'copy gain', subclassof: ['copy variant']},
    {name: 'copy loss', subclassof: ['copy variant']},
    {name: 'copy variant', subclassof: ['mutation']},
    {name: 'decreased dosage', subclassof: ['dosage']},
    {name: 'decreased metabolism', subclassof: ['metabolism']},
    {name: 'decreased toxicity', subclassof: ['toxicity']},
    {name: 'deletion', subclassof: ['indel', 'copy loss']},
    {name: 'diagnostic indicator', description: 'evidence is diagnostic for a specific disease type, disease subtype or disease state'},
    {name: 'disruptive fusion', description: 'fusion disrupts the wild-type functionality of one or more of its fusion partners'},
    {name: 'dominant gain of function', subclassof: ['gain of function'], description: 'an event whose product adversely affects the normal product resulting in a gain-of-function phenotype'},
    {name: 'dominant negative', subclassof: ['loss of function'], description: 'an event whose product adversely affects the normal product resulting in a loss-of-function phenotype'},
    {name: 'dosage', subclassof: ['therapeutic indicator']},
    {name: 'duplication', subclassof: ['mutation']},
    {name: 'eligibility'},
    {name: 'expression variant', subclassof: ['biological']},
    {name: 'extension', subclassof: ['mutation']},
    {name: 'favourable prognosis', subclassof: ['prognostic indicator'], description: 'event imparts a favourable outcome'},
    {name: 'favours diagnosis', subclassof: ['diagnostic indicator']},
    {name: 'focal amplification', subclassof: ['amplification']},
    {name: 'frameshift', subclassof: ['mutation']},
    {name: 'functional effect', oppositeof: ['no functional effect'], subclassof: ['biological']},
    {name: 'fusion', subclassof: ['mutation']},
    {name: 'gain of function', subclassof: ['increased function'], oppositeof: ['loss of function'], description: 'event imparts an acquired function on the product leading to a specific observable phenotype'},
    {name: 'haploinsufficient', subclassof: ['tumour suppressive'], description: 'an event leading to loss of function in a product that is dosage dependant such that the incomplete loss of function leads to an observable phenotype when event is in a heterozygous state'},
    {name: 'in-frame deletion', subclassof: ['deletion']},
    {name: 'in-frameshift insertion', subclassof: ['insertion']},
    {name: 'increased dosage', subclassof: ['dosage']},
    {name: 'increased expression', subclassof: ['expression variant'], aliasof: ['overexpression', 'up-regulated expression']},
    {name: 'increased function', subclassof: ['functional effect'], oppositeof: ['reduced function'], description: 'the efficacy or frequency of the existing functionality is increased'},
    {name: 'increased metabolism', subclassof: ['metabolism']},
    {name: 'increased metastasis', subclassof: ['unfavourable prognosis']},
    {name: 'increased protein expression', subclassof: ['protein expression variant', 'increased expression'], aliasof: ['protein overexpression', 'up-regulated protein expression']},
    {name: 'increased rna expression', subclassof: ['rna expression variant', 'increased expression'], aliasof: ['rna overexpression', 'up-regulated rna expression']},
    {name: 'increased survival', subclassof: ['favourable prognosis']},
    {name: 'increased toxicity', subclassof: ['toxicity']},
    {name: 'indel', subclassof: ['mutation']},
    {name: 'innate resistance', subclassof: ['resistance']},
    {name: 'insertion', subclassof: ['indel']},
    {name: 'internal tandem duplication (ITD)', subclassof: ['tandem duplication']},
    {name: 'inversion', subclassof: ['mutation']},
    {name: 'inverted translocation', subclassof: ['translocation']},
    {name: 'is characteristic of', subclassof: ['favours diagnosis'], description: 'a hallmark of this disease type'},
    {name: 'likely gain of function', subclassof: ['gain of function'], description: 'gain-of-function is predicted or assumed (by the literature) based on an inference of similar events or data'},
    {name: 'likely loss of function', subclassof: ['loss of function'], description: 'loss-of-function is predicted or assumed (by the literature) based on an inference of similar events or data'},
    {name: 'likely no functional effect', subclassof: ['no functional effect']},
    {name: 'likely oncogenic', subclassof: ['oncogenic']},
    {name: 'likely resistance', subclassof: ['resistance']},
    {name: 'likely sensitivity', subclassof: ['sensitivity']},
    {name: 'likely switch of function', subclassof: ['switch of function']},
    {name: 'likely tumour suppressive', subclassof: ['tumour suppressive']},
    {name: 'loss of function', subclassof: ['reduced function'], description: 'some normal functionality has been lost'},
    {name: 'metabolism', subclassof: ['therapeutic indicator']},
    {name: 'missense mutation', subclassof: ['substitution']},
    {name: 'mutation hotspot', subclassof: ['recurrent'], description: 'the specific residue noted has been observed to be recurrently and commonly mutated at some signifiant frequency above random in numerrous independent observations'},
    {name: 'mutation', subclassof: ['biological'], description: 'generally small mutations or intra-chromosomal rearrangements'},
    {name: 'no functional effect', subclassof: ['biological'], description: 'does not result in altered functionality as compared to the wild-type'},
    {name: 'no gain of function', subclassof: ['no functional effect'], oppositeof: ['gain of function'], description: 'does not result in gain-of-function'},
    {name: 'no loss of function', subclassof: ['no functional effect'], oppositeof: ['loss of function'], description: 'does not result in loss-of-function'},
    {name: 'no protein expression', subclassof: ['protein expression variant', 'no expression']},
    {name: 'no resistance', subclassof: ['therapeutic efficacy'], oppositeof: ['resistance'], description: 'does not confer increased resistance as compared to wild-type state'},
    {name: 'no response', subclassof: ['no sensitivity'], oppositeof: ['response']},
    {name: 'no rna expression', subclassof: ['rna expression variant', 'no expression']},
    {name: 'no sensitivity', subclassof: ['therapeutic efficacy'], oppositeof: ['sensitivity'], description: 'does not confer increased sensitivity as compared to wild-type state'},
    {name: 'no switch of function', subclassof: ['no functional effect'], oppositeof: ['switch of function']},
    {name: 'oncogenic fusion', subclassof: ['oncogenic', 'fusion'], description: 'fusion whose product promotes cancer'},
    {name: 'oncogenic', subclassof: ['tumourigenesis'], description: 'having the potential to cause a normal cell to become cancerous'},
    {name: 'opposes diagnosis', subclassof: ['diagnostic indicator']},
    {name: 'pathogenic', subclassof: ['biological']},
    {name: 'prognostic indicator'},
    {name: 'protein expression variant', subclassof: ['expression variant']},
    {name: 'recurrent', subclassof: ['biological'], description: 'commonly observed'},
    {name: 'reduced expression', subclassof: ['expression variant'], aliasof: ['underexpression', 'down-regulated expression']},
    {name: 'reduced function', subclassof: ['functional effect'], description: 'the efficacy or frequency of the existing functionality is reduced'},
    {name: 'reduced protein expression', subclassof: ['protein expression variant'], aliasof: ['down-regulated protein expression', 'protein underexpression']},
    {name: 'reduced rna expression', subclassof: ['rna expression variant'], aliasof: ['down-regulated rna expression', 'rna underexpression']},
    {name: 'reduced sensitivity', subclassof: ['resistance']},
    {name: 'relapse', subclassof: ['unfavourable prognosis']},
    {name: 'resistance', subclassof: ['no response']},
    {name: 'response', subclassof: ['no resistance', 'targetable']},
    {name: 'rna expression variant', subclassof: ['expression variant']},
    {name: 'sensitivity', subclassof: ['response']},
    {name: 'splice-site', subclassof: ['mutation']},
    {name: 'start gain', subclassof: ['extension']},
    {name: 'stop loss', subclassof: ['extension']},
    {name: 'substitution', subclassof: ['mutation']},
    {name: 'switch of function', subclassof: ['functional effect'], description: 'some wild-type/normal functionality is lost and some novel functionality is gained'},
    {name: 'tandem duplication', subclassof: ['duplication']},
    {name: 'targetable', subclassof: ['therapeutic efficacy'], description: 'therapy can be used given some event or combination of event'},
    {name: 'therapeutic efficacy', subclassof: ['therapeutic indicator']},
    {name: 'therapeutic indicator', aliasof: ['pharmacogenomic']},
    {name: 'toxicity', subclassof: ['therapeutic indicator']},
    {name: 'translocation', subclassof: ['mutation']},
    {name: 'truncating', subclassof: ['mutation']},
    {name: 'tumour suppressive', subclassof: ['tumourigenesis'], description: 'suppresses or blocks the development of cancer'},
    {name: 'tumourigenesis', subclassof: ['biological']},
    {name: 'unfavourable prognosis', subclassof: ['prognostic indicator'], description: 'event is associated with a specifed, unfavouable outcome'}
];

module.exports = {VOCABULARY};