name: build

on:
  - push


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    name: node-${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint -- --quiet # errors only, no warnings
        name: eslint
      - run: npm audit --production --audit-level high
        if: ${{ github.base_ref == 'master' }}
      - run: npm run test
      - uses: EnricoMi/publish-unit-test-result-action@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: coverage/junit.xml
        if: matrix.node == 14
  docker:
    runs-on: ubuntu-latest
    name: docker build
    steps:
      - uses: actions/checkout@v2
      - name: build the docker container
        run: |
          docker build --file Dockerfile --tag bcgsc/pori-graphkb-loader .
